base:
    is_dev: false
    serial_number: 1.0.0
    service_name: shares
    service_displayname: sharesserver
    sercice_desc: shares微服务

tools_type: 0 # 0:正式环境,1:日分析,2:抓取消息,3:放量,4:放量监听

db_info:
    host: localhost
    port: 3306
    username: root
    password: 123456
    database: caoguo_dev

redis_info:
    addrs: ["127.0.0.1:6379"]
    password: ""
    group_name: oauth2
    db: 0

etcd_info:
    addrs: ["127.0.0.1:2379"]
    timeout: 3

security:
    allowed_origins: []
    allow_credentials: false
    cookie_secure: null
    cookie_same_site: lax
    cookie_domain: ""
    enable_metrics: false

port: 8082
file_host: https://www.localhost.com/shares/api/v1
max_capacity: 5
def_group: 默认指标
ext: [sh, sz, hk]

adata:
    concepts_url: ""
    python: python3
    script: ./scripts/adata_concepts.py
    args: []
